version: '3'
services:
  db:
    image: 'postgres'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres1
    # env_file:
    #   - ./env/postgres.env # you can also define env variables like this.
  rails:
    build: ./ 
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container

volumes:
  postgres: # named volume