app = 'catbreed-dry-frog-7835'
primary_region = "arn"
console_command = "/bin/bash"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "./bin/rails db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
